TARGET = out
CFLAGS = -std=c++17
CC = g++

all: $(TARGET)

$(TARGET): main.cpp MaxProduct.h MaxProduct.h MaxProduct.cpp
		$(CC) $(CFLAGS) -o $(TARGET) main.cpp MaxProduct.h MaxProduct.h MaxProduct.cpp
