# Simply execute "make" in working directory to create executable "problem5"
# Running "make clean" will remove the executable

# If you use additional files, you will need to modify the line 9 accordingly

# PLEASE TEST YOUR MAKEFILE TO ENSURE IT WORKS BEFORE SUBMITTING

all:
	g++ -std=c++17 Huffman.cpp main.cpp -o problem5
clean:
	rm problem5
